// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package listing

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDe046902EncodeGithubComIfreddyrondonCaptureAppListing(out *jwriter.Writer, in Listing) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"paging\":")
	out.Raw((in.Paging).MarshalJSON())
	if in.Sort != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"sort\":")
		if in.Sort == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.Sort).MarshalJSON())
		}
	}
	if len(in.Available) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"available\":")
		if in.Available == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Available {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Raw((v3).MarshalJSON())
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
