// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package payload

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ad23cceDecodeGithubComIfreddyrondonCapturePayload(in *jlexer.Lexer, out *payloadJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cap":
			if in.IsNull() {
				in.Skip()
				out.Cap = nil
			} else {
				in.Delim('[')
				if out.Cap == nil {
					if !in.IsDelim(']') {
						out.Cap = make([]*Metric, 0, 8)
					} else {
						out.Cap = []*Metric{}
					}
				} else {
					out.Cap = (out.Cap)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Metric
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Metric)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v1).UnmarshalJSON(data))
						}
					}
					out.Cap = append(out.Cap, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "captures":
			if in.IsNull() {
				in.Skip()
				out.Captures = nil
			} else {
				in.Delim('[')
				if out.Captures == nil {
					if !in.IsDelim(']') {
						out.Captures = make([]*Metric, 0, 8)
					} else {
						out.Captures = []*Metric{}
					}
				} else {
					out.Captures = (out.Captures)[:0]
				}
				for !in.IsDelim(']') {
					var v2 *Metric
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						if v2 == nil {
							v2 = new(Metric)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v2).UnmarshalJSON(data))
						}
					}
					out.Captures = append(out.Captures, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]*Metric, 0, 8)
					} else {
						out.Data = []*Metric{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v3 *Metric
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(Metric)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v3).UnmarshalJSON(data))
						}
					}
					out.Data = append(out.Data, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "payload":
			if in.IsNull() {
				in.Skip()
				out.Payload = nil
			} else {
				in.Delim('[')
				if out.Payload == nil {
					if !in.IsDelim(']') {
						out.Payload = make([]*Metric, 0, 8)
					} else {
						out.Payload = []*Metric{}
					}
				} else {
					out.Payload = (out.Payload)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *Metric
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(Metric)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v4).UnmarshalJSON(data))
						}
					}
					out.Payload = append(out.Payload, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
