// generated by "charlatan -output=user_store_charlatan_test.go Store".  DO NOT EDIT.

package user

import "reflect"

// StoreSaveInvocation represents a single call of FakeStore.Save
type StoreSaveInvocation struct {
	Parameters struct {
		Ident1 *User
	}
	Results struct {
		Ident2 error
	}
}

// NewStoreSaveInvocation creates a new instance of StoreSaveInvocation
func NewStoreSaveInvocation(ident1 *User, ident2 error) *StoreSaveInvocation {
	invocation := new(StoreSaveInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2

	return invocation
}

// StoreGetInvocation represents a single call of FakeStore.Get
type StoreGetInvocation struct {
	Parameters struct {
		Ident1 string
	}
	Results struct {
		Ident2 *User
		Ident3 error
	}
}

// NewStoreGetInvocation creates a new instance of StoreGetInvocation
func NewStoreGetInvocation(ident1 string, ident2 *User, ident3 error) *StoreGetInvocation {
	invocation := new(StoreGetInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2
	invocation.Results.Ident3 = ident3

	return invocation
}

// StoreTestingT represents the methods of "testing".T used by charlatan Fakes.  It avoids importing the testing package.
type StoreTestingT interface {
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Helper()
}

/*
FakeStore is a mock implementation of Store for testing.
Use it in your tests as in this example:

	package example

	func TestWithStore(t *testing.T) {
		f := &user.FakeStore{
			SaveHook: func(ident1 *User) (ident2 error) {
				// ensure parameters meet expections, signal errors using t, etc
				return
			},
		}

		// test code goes here ...

		// assert state of FakeSave ...
		f.AssertSaveCalledOnce(t)
	}

Create anonymous function implementations for only those interface methods that
should be called in the code under test.  This will force a panic if any
unexpected calls are made to FakeSave.
*/
type FakeStore struct {
	SaveHook func(*User) error
	GetHook  func(string) (*User, error)

	SaveCalls []*StoreSaveInvocation
	GetCalls  []*StoreGetInvocation
}

// NewFakeStoreDefaultPanic returns an instance of FakeStore with all hooks configured to panic
func NewFakeStoreDefaultPanic() *FakeStore {
	return &FakeStore{
		SaveHook: func(*User) (ident2 error) {
			panic("Unexpected call to Store.Save")
		},
		GetHook: func(string) (ident2 *User, ident3 error) {
			panic("Unexpected call to Store.Get")
		},
	}
}

// NewFakeStoreDefaultFatal returns an instance of FakeStore with all hooks configured to call t.Fatal
func NewFakeStoreDefaultFatal(t_sym1 StoreTestingT) *FakeStore {
	return &FakeStore{
		SaveHook: func(*User) (ident2 error) {
			t_sym1.Fatal("Unexpected call to Store.Save")
			return
		},
		GetHook: func(string) (ident2 *User, ident3 error) {
			t_sym1.Fatal("Unexpected call to Store.Get")
			return
		},
	}
}

// NewFakeStoreDefaultError returns an instance of FakeStore with all hooks configured to call t.Error
func NewFakeStoreDefaultError(t_sym2 StoreTestingT) *FakeStore {
	return &FakeStore{
		SaveHook: func(*User) (ident2 error) {
			t_sym2.Error("Unexpected call to Store.Save")
			return
		},
		GetHook: func(string) (ident2 *User, ident3 error) {
			t_sym2.Error("Unexpected call to Store.Get")
			return
		},
	}
}

func (f *FakeStore) Reset() {
	f.SaveCalls = []*StoreSaveInvocation{}
	f.GetCalls = []*StoreGetInvocation{}
}

func (f_sym3 *FakeStore) Save(ident1 *User) (ident2 error) {
	if f_sym3.SaveHook == nil {
		panic("Store.Save() called but FakeStore.SaveHook is nil")
	}

	invocation_sym3 := new(StoreSaveInvocation)
	f_sym3.SaveCalls = append(f_sym3.SaveCalls, invocation_sym3)

	invocation_sym3.Parameters.Ident1 = ident1

	ident2 = f_sym3.SaveHook(ident1)

	invocation_sym3.Results.Ident2 = ident2

	return
}

// SetSaveStub configures Store.Save to always return the given values
func (f_sym4 *FakeStore) SetSaveStub(ident2 error) {
	f_sym4.SaveHook = func(*User) error {
		return ident2
	}
}

// SetSaveInvocation configures Store.Save to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym5 *FakeStore) SetSaveInvocation(calls_sym5 []*StoreSaveInvocation, fallback_sym5 func() error) {
	f_sym5.SaveHook = func(ident1 *User) (ident2 error) {
		for _, call_sym5 := range calls_sym5 {
			if reflect.DeepEqual(call_sym5.Parameters.Ident1, ident1) {
				ident2 = call_sym5.Results.Ident2

				return
			}
		}

		return fallback_sym5()
	}
}

// SaveCalled returns true if FakeStore.Save was called
func (f *FakeStore) SaveCalled() bool {
	return len(f.SaveCalls) != 0
}

// AssertSaveCalled calls t.Error if FakeStore.Save was not called
func (f *FakeStore) AssertSaveCalled(t StoreTestingT) {
	t.Helper()
	if len(f.SaveCalls) == 0 {
		t.Error("FakeStore.Save not called, expected at least one")
	}
}

// SaveNotCalled returns true if FakeStore.Save was not called
func (f *FakeStore) SaveNotCalled() bool {
	return len(f.SaveCalls) == 0
}

// AssertSaveNotCalled calls t.Error if FakeStore.Save was called
func (f *FakeStore) AssertSaveNotCalled(t StoreTestingT) {
	t.Helper()
	if len(f.SaveCalls) != 0 {
		t.Error("FakeStore.Save called, expected none")
	}
}

// SaveCalledOnce returns true if FakeStore.Save was called exactly once
func (f *FakeStore) SaveCalledOnce() bool {
	return len(f.SaveCalls) == 1
}

// AssertSaveCalledOnce calls t.Error if FakeStore.Save was not called exactly once
func (f *FakeStore) AssertSaveCalledOnce(t StoreTestingT) {
	t.Helper()
	if len(f.SaveCalls) != 1 {
		t.Errorf("FakeStore.Save called %d times, expected 1", len(f.SaveCalls))
	}
}

// SaveCalledN returns true if FakeStore.Save was called at least n times
func (f *FakeStore) SaveCalledN(n int) bool {
	return len(f.SaveCalls) >= n
}

// AssertSaveCalledN calls t.Error if FakeStore.Save was called less than n times
func (f *FakeStore) AssertSaveCalledN(t StoreTestingT, n int) {
	t.Helper()
	if len(f.SaveCalls) < n {
		t.Errorf("FakeStore.Save called %d times, expected >= %d", len(f.SaveCalls), n)
	}
}

// SaveCalledWith returns true if FakeStore.Save was called with the given values
func (f_sym6 *FakeStore) SaveCalledWith(ident1 *User) bool {
	for _, call_sym6 := range f_sym6.SaveCalls {
		if reflect.DeepEqual(call_sym6.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertSaveCalledWith calls t.Error if FakeStore.Save was not called with the given values
func (f_sym7 *FakeStore) AssertSaveCalledWith(t StoreTestingT, ident1 *User) {
	t.Helper()
	var found_sym7 bool
	for _, call_sym7 := range f_sym7.SaveCalls {
		if reflect.DeepEqual(call_sym7.Parameters.Ident1, ident1) {
			found_sym7 = true
			break
		}
	}

	if !found_sym7 {
		t.Error("FakeStore.Save not called with expected parameters")
	}
}

// SaveCalledOnceWith returns true if FakeStore.Save was called exactly once with the given values
func (f_sym8 *FakeStore) SaveCalledOnceWith(ident1 *User) bool {
	var count_sym8 int
	for _, call_sym8 := range f_sym8.SaveCalls {
		if reflect.DeepEqual(call_sym8.Parameters.Ident1, ident1) {
			count_sym8++
		}
	}

	return count_sym8 == 1
}

// AssertSaveCalledOnceWith calls t.Error if FakeStore.Save was not called exactly once with the given values
func (f_sym9 *FakeStore) AssertSaveCalledOnceWith(t StoreTestingT, ident1 *User) {
	t.Helper()
	var count_sym9 int
	for _, call_sym9 := range f_sym9.SaveCalls {
		if reflect.DeepEqual(call_sym9.Parameters.Ident1, ident1) {
			count_sym9++
		}
	}

	if count_sym9 != 1 {
		t.Errorf("FakeStore.Save called %d times with expected parameters, expected one", count_sym9)
	}
}

// SaveResultsForCall returns the result values for the first call to FakeStore.Save with the given values
func (f_sym10 *FakeStore) SaveResultsForCall(ident1 *User) (ident2 error, found_sym10 bool) {
	for _, call_sym10 := range f_sym10.SaveCalls {
		if reflect.DeepEqual(call_sym10.Parameters.Ident1, ident1) {
			ident2 = call_sym10.Results.Ident2
			found_sym10 = true
			break
		}
	}

	return
}

func (f_sym11 *FakeStore) Get(ident1 string) (ident2 *User, ident3 error) {
	if f_sym11.GetHook == nil {
		panic("Store.Get() called but FakeStore.GetHook is nil")
	}

	invocation_sym11 := new(StoreGetInvocation)
	f_sym11.GetCalls = append(f_sym11.GetCalls, invocation_sym11)

	invocation_sym11.Parameters.Ident1 = ident1

	ident2, ident3 = f_sym11.GetHook(ident1)

	invocation_sym11.Results.Ident2 = ident2
	invocation_sym11.Results.Ident3 = ident3

	return
}

// SetGetStub configures Store.Get to always return the given values
func (f_sym12 *FakeStore) SetGetStub(ident2 *User, ident3 error) {
	f_sym12.GetHook = func(string) (*User, error) {
		return ident2, ident3
	}
}

// SetGetInvocation configures Store.Get to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym13 *FakeStore) SetGetInvocation(calls_sym13 []*StoreGetInvocation, fallback_sym13 func() (*User, error)) {
	f_sym13.GetHook = func(ident1 string) (ident2 *User, ident3 error) {
		for _, call_sym13 := range calls_sym13 {
			if reflect.DeepEqual(call_sym13.Parameters.Ident1, ident1) {
				ident2 = call_sym13.Results.Ident2
				ident3 = call_sym13.Results.Ident3

				return
			}
		}

		return fallback_sym13()
	}
}

// GetCalled returns true if FakeStore.Get was called
func (f *FakeStore) GetCalled() bool {
	return len(f.GetCalls) != 0
}

// AssertGetCalled calls t.Error if FakeStore.Get was not called
func (f *FakeStore) AssertGetCalled(t StoreTestingT) {
	t.Helper()
	if len(f.GetCalls) == 0 {
		t.Error("FakeStore.Get not called, expected at least one")
	}
}

// GetNotCalled returns true if FakeStore.Get was not called
func (f *FakeStore) GetNotCalled() bool {
	return len(f.GetCalls) == 0
}

// AssertGetNotCalled calls t.Error if FakeStore.Get was called
func (f *FakeStore) AssertGetNotCalled(t StoreTestingT) {
	t.Helper()
	if len(f.GetCalls) != 0 {
		t.Error("FakeStore.Get called, expected none")
	}
}

// GetCalledOnce returns true if FakeStore.Get was called exactly once
func (f *FakeStore) GetCalledOnce() bool {
	return len(f.GetCalls) == 1
}

// AssertGetCalledOnce calls t.Error if FakeStore.Get was not called exactly once
func (f *FakeStore) AssertGetCalledOnce(t StoreTestingT) {
	t.Helper()
	if len(f.GetCalls) != 1 {
		t.Errorf("FakeStore.Get called %d times, expected 1", len(f.GetCalls))
	}
}

// GetCalledN returns true if FakeStore.Get was called at least n times
func (f *FakeStore) GetCalledN(n int) bool {
	return len(f.GetCalls) >= n
}

// AssertGetCalledN calls t.Error if FakeStore.Get was called less than n times
func (f *FakeStore) AssertGetCalledN(t StoreTestingT, n int) {
	t.Helper()
	if len(f.GetCalls) < n {
		t.Errorf("FakeStore.Get called %d times, expected >= %d", len(f.GetCalls), n)
	}
}

// GetCalledWith returns true if FakeStore.Get was called with the given values
func (f_sym14 *FakeStore) GetCalledWith(ident1 string) bool {
	for _, call_sym14 := range f_sym14.GetCalls {
		if reflect.DeepEqual(call_sym14.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertGetCalledWith calls t.Error if FakeStore.Get was not called with the given values
func (f_sym15 *FakeStore) AssertGetCalledWith(t StoreTestingT, ident1 string) {
	t.Helper()
	var found_sym15 bool
	for _, call_sym15 := range f_sym15.GetCalls {
		if reflect.DeepEqual(call_sym15.Parameters.Ident1, ident1) {
			found_sym15 = true
			break
		}
	}

	if !found_sym15 {
		t.Error("FakeStore.Get not called with expected parameters")
	}
}

// GetCalledOnceWith returns true if FakeStore.Get was called exactly once with the given values
func (f_sym16 *FakeStore) GetCalledOnceWith(ident1 string) bool {
	var count_sym16 int
	for _, call_sym16 := range f_sym16.GetCalls {
		if reflect.DeepEqual(call_sym16.Parameters.Ident1, ident1) {
			count_sym16++
		}
	}

	return count_sym16 == 1
}

// AssertGetCalledOnceWith calls t.Error if FakeStore.Get was not called exactly once with the given values
func (f_sym17 *FakeStore) AssertGetCalledOnceWith(t StoreTestingT, ident1 string) {
	t.Helper()
	var count_sym17 int
	for _, call_sym17 := range f_sym17.GetCalls {
		if reflect.DeepEqual(call_sym17.Parameters.Ident1, ident1) {
			count_sym17++
		}
	}

	if count_sym17 != 1 {
		t.Errorf("FakeStore.Get called %d times with expected parameters, expected one", count_sym17)
	}
}

// GetResultsForCall returns the result values for the first call to FakeStore.Get with the given values
func (f_sym18 *FakeStore) GetResultsForCall(ident1 string) (ident2 *User, ident3 error, found_sym18 bool) {
	for _, call_sym18 := range f_sym18.GetCalls {
		if reflect.DeepEqual(call_sym18.Parameters.Ident1, ident1) {
			ident2 = call_sym18.Results.Ident2
			ident3 = call_sym18.Results.Ident3
			found_sym18 = true
			break
		}
	}

	return
}
