// generated by "charlatan -output=user_store_charlatan_test.go Store".  DO NOT EDIT.

package user

import "reflect"

import kallax "gopkg.in/src-d/go-kallax.v1"

// StoreSaveInvocation represents a single call of FakeStore.Save
type StoreSaveInvocation struct {
	Parameters struct {
		Ident1 *User
	}
	Results struct {
		Ident2 error
	}
}

// NewStoreSaveInvocation creates a new instance of StoreSaveInvocation
func NewStoreSaveInvocation(ident1 *User, ident2 error) *StoreSaveInvocation {
	invocation := new(StoreSaveInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2

	return invocation
}

// StoreGetByEmailInvocation represents a single call of FakeStore.GetByEmail
type StoreGetByEmailInvocation struct {
	Parameters struct {
		Ident1 string
	}
	Results struct {
		Ident2 *User
		Ident3 error
	}
}

// NewStoreGetByEmailInvocation creates a new instance of StoreGetByEmailInvocation
func NewStoreGetByEmailInvocation(ident1 string, ident2 *User, ident3 error) *StoreGetByEmailInvocation {
	invocation := new(StoreGetByEmailInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2
	invocation.Results.Ident3 = ident3

	return invocation
}

// StoreGetByIDInvocation represents a single call of FakeStore.GetByID
type StoreGetByIDInvocation struct {
	Parameters struct {
		Ident1 kallax.ULID
	}
	Results struct {
		Ident2 *User
		Ident3 error
	}
}

// NewStoreGetByIDInvocation creates a new instance of StoreGetByIDInvocation
func NewStoreGetByIDInvocation(ident1 kallax.ULID, ident2 *User, ident3 error) *StoreGetByIDInvocation {
	invocation := new(StoreGetByIDInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2
	invocation.Results.Ident3 = ident3

	return invocation
}

// StoreTestingT represents the methods of "testing".T used by charlatan Fakes.  It avoids importing the testing package.
type StoreTestingT interface {
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Helper()
}

/*
FakeStore is a mock implementation of Store for testing.
Use it in your tests as in this example:

	package example

	func TestWithStore(t *testing.T) {
		f := &user.FakeStore{
			SaveHook: func(ident1 *User) (ident2 error) {
				// ensure parameters meet expections, signal errors using t, etc
				return
			},
		}

		// test code goes here ...

		// assert state of FakeSave ...
		f.AssertSaveCalledOnce(t)
	}

Create anonymous function implementations for only those interface methods that
should be called in the code under test.  This will force a panic if any
unexpected calls are made to FakeSave.
*/
type FakeStore struct {
	SaveHook       func(*User) error
	GetByEmailHook func(string) (*User, error)
	GetByIDHook    func(kallax.ULID) (*User, error)

	SaveCalls       []*StoreSaveInvocation
	GetByEmailCalls []*StoreGetByEmailInvocation
	GetByIDCalls    []*StoreGetByIDInvocation
}

// NewFakeStoreDefaultPanic returns an instance of FakeStore with all hooks configured to panic
func NewFakeStoreDefaultPanic() *FakeStore {
	return &FakeStore{
		SaveHook: func(*User) (ident2 error) {
			panic("Unexpected call to Store.Save")
		},
		GetByEmailHook: func(string) (ident2 *User, ident3 error) {
			panic("Unexpected call to Store.GetByEmail")
		},
		GetByIDHook: func(kallax.ULID) (ident2 *User, ident3 error) {
			panic("Unexpected call to Store.GetByID")
		},
	}
}

// NewFakeStoreDefaultFatal returns an instance of FakeStore with all hooks configured to call t.Fatal
func NewFakeStoreDefaultFatal(t_sym1 StoreTestingT) *FakeStore {
	return &FakeStore{
		SaveHook: func(*User) (ident2 error) {
			t_sym1.Fatal("Unexpected call to Store.Save")
			return
		},
		GetByEmailHook: func(string) (ident2 *User, ident3 error) {
			t_sym1.Fatal("Unexpected call to Store.GetByEmail")
			return
		},
		GetByIDHook: func(kallax.ULID) (ident2 *User, ident3 error) {
			t_sym1.Fatal("Unexpected call to Store.GetByID")
			return
		},
	}
}

// NewFakeStoreDefaultError returns an instance of FakeStore with all hooks configured to call t.Error
func NewFakeStoreDefaultError(t_sym2 StoreTestingT) *FakeStore {
	return &FakeStore{
		SaveHook: func(*User) (ident2 error) {
			t_sym2.Error("Unexpected call to Store.Save")
			return
		},
		GetByEmailHook: func(string) (ident2 *User, ident3 error) {
			t_sym2.Error("Unexpected call to Store.GetByEmail")
			return
		},
		GetByIDHook: func(kallax.ULID) (ident2 *User, ident3 error) {
			t_sym2.Error("Unexpected call to Store.GetByID")
			return
		},
	}
}

func (f *FakeStore) Reset() {
	f.SaveCalls = []*StoreSaveInvocation{}
	f.GetByEmailCalls = []*StoreGetByEmailInvocation{}
	f.GetByIDCalls = []*StoreGetByIDInvocation{}
}

func (f_sym3 *FakeStore) Save(ident1 *User) (ident2 error) {
	if f_sym3.SaveHook == nil {
		panic("Store.Save() called but FakeStore.SaveHook is nil")
	}

	invocation_sym3 := new(StoreSaveInvocation)
	f_sym3.SaveCalls = append(f_sym3.SaveCalls, invocation_sym3)

	invocation_sym3.Parameters.Ident1 = ident1

	ident2 = f_sym3.SaveHook(ident1)

	invocation_sym3.Results.Ident2 = ident2

	return
}

// SetSaveStub configures Store.Save to always return the given values
func (f_sym4 *FakeStore) SetSaveStub(ident2 error) {
	f_sym4.SaveHook = func(*User) error {
		return ident2
	}
}

// SetSaveInvocation configures Store.Save to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym5 *FakeStore) SetSaveInvocation(calls_sym5 []*StoreSaveInvocation, fallback_sym5 func() error) {
	f_sym5.SaveHook = func(ident1 *User) (ident2 error) {
		for _, call_sym5 := range calls_sym5 {
			if reflect.DeepEqual(call_sym5.Parameters.Ident1, ident1) {
				ident2 = call_sym5.Results.Ident2

				return
			}
		}

		return fallback_sym5()
	}
}

// SaveCalled returns true if FakeStore.Save was called
func (f *FakeStore) SaveCalled() bool {
	return len(f.SaveCalls) != 0
}

// AssertSaveCalled calls t.Error if FakeStore.Save was not called
func (f *FakeStore) AssertSaveCalled(t StoreTestingT) {
	t.Helper()
	if len(f.SaveCalls) == 0 {
		t.Error("FakeStore.Save not called, expected at least one")
	}
}

// SaveNotCalled returns true if FakeStore.Save was not called
func (f *FakeStore) SaveNotCalled() bool {
	return len(f.SaveCalls) == 0
}

// AssertSaveNotCalled calls t.Error if FakeStore.Save was called
func (f *FakeStore) AssertSaveNotCalled(t StoreTestingT) {
	t.Helper()
	if len(f.SaveCalls) != 0 {
		t.Error("FakeStore.Save called, expected none")
	}
}

// SaveCalledOnce returns true if FakeStore.Save was called exactly once
func (f *FakeStore) SaveCalledOnce() bool {
	return len(f.SaveCalls) == 1
}

// AssertSaveCalledOnce calls t.Error if FakeStore.Save was not called exactly once
func (f *FakeStore) AssertSaveCalledOnce(t StoreTestingT) {
	t.Helper()
	if len(f.SaveCalls) != 1 {
		t.Errorf("FakeStore.Save called %d times, expected 1", len(f.SaveCalls))
	}
}

// SaveCalledN returns true if FakeStore.Save was called at least n times
func (f *FakeStore) SaveCalledN(n int) bool {
	return len(f.SaveCalls) >= n
}

// AssertSaveCalledN calls t.Error if FakeStore.Save was called less than n times
func (f *FakeStore) AssertSaveCalledN(t StoreTestingT, n int) {
	t.Helper()
	if len(f.SaveCalls) < n {
		t.Errorf("FakeStore.Save called %d times, expected >= %d", len(f.SaveCalls), n)
	}
}

// SaveCalledWith returns true if FakeStore.Save was called with the given values
func (f_sym6 *FakeStore) SaveCalledWith(ident1 *User) bool {
	for _, call_sym6 := range f_sym6.SaveCalls {
		if reflect.DeepEqual(call_sym6.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertSaveCalledWith calls t.Error if FakeStore.Save was not called with the given values
func (f_sym7 *FakeStore) AssertSaveCalledWith(t StoreTestingT, ident1 *User) {
	t.Helper()
	var found_sym7 bool
	for _, call_sym7 := range f_sym7.SaveCalls {
		if reflect.DeepEqual(call_sym7.Parameters.Ident1, ident1) {
			found_sym7 = true
			break
		}
	}

	if !found_sym7 {
		t.Error("FakeStore.Save not called with expected parameters")
	}
}

// SaveCalledOnceWith returns true if FakeStore.Save was called exactly once with the given values
func (f_sym8 *FakeStore) SaveCalledOnceWith(ident1 *User) bool {
	var count_sym8 int
	for _, call_sym8 := range f_sym8.SaveCalls {
		if reflect.DeepEqual(call_sym8.Parameters.Ident1, ident1) {
			count_sym8++
		}
	}

	return count_sym8 == 1
}

// AssertSaveCalledOnceWith calls t.Error if FakeStore.Save was not called exactly once with the given values
func (f_sym9 *FakeStore) AssertSaveCalledOnceWith(t StoreTestingT, ident1 *User) {
	t.Helper()
	var count_sym9 int
	for _, call_sym9 := range f_sym9.SaveCalls {
		if reflect.DeepEqual(call_sym9.Parameters.Ident1, ident1) {
			count_sym9++
		}
	}

	if count_sym9 != 1 {
		t.Errorf("FakeStore.Save called %d times with expected parameters, expected one", count_sym9)
	}
}

// SaveResultsForCall returns the result values for the first call to FakeStore.Save with the given values
func (f_sym10 *FakeStore) SaveResultsForCall(ident1 *User) (ident2 error, found_sym10 bool) {
	for _, call_sym10 := range f_sym10.SaveCalls {
		if reflect.DeepEqual(call_sym10.Parameters.Ident1, ident1) {
			ident2 = call_sym10.Results.Ident2
			found_sym10 = true
			break
		}
	}

	return
}

func (f_sym11 *FakeStore) GetByEmail(ident1 string) (ident2 *User, ident3 error) {
	if f_sym11.GetByEmailHook == nil {
		panic("Store.GetByEmail() called but FakeStore.GetByEmailHook is nil")
	}

	invocation_sym11 := new(StoreGetByEmailInvocation)
	f_sym11.GetByEmailCalls = append(f_sym11.GetByEmailCalls, invocation_sym11)

	invocation_sym11.Parameters.Ident1 = ident1

	ident2, ident3 = f_sym11.GetByEmailHook(ident1)

	invocation_sym11.Results.Ident2 = ident2
	invocation_sym11.Results.Ident3 = ident3

	return
}

// SetGetByEmailStub configures Store.GetByEmail to always return the given values
func (f_sym12 *FakeStore) SetGetByEmailStub(ident2 *User, ident3 error) {
	f_sym12.GetByEmailHook = func(string) (*User, error) {
		return ident2, ident3
	}
}

// SetGetByEmailInvocation configures Store.GetByEmail to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym13 *FakeStore) SetGetByEmailInvocation(calls_sym13 []*StoreGetByEmailInvocation, fallback_sym13 func() (*User, error)) {
	f_sym13.GetByEmailHook = func(ident1 string) (ident2 *User, ident3 error) {
		for _, call_sym13 := range calls_sym13 {
			if reflect.DeepEqual(call_sym13.Parameters.Ident1, ident1) {
				ident2 = call_sym13.Results.Ident2
				ident3 = call_sym13.Results.Ident3

				return
			}
		}

		return fallback_sym13()
	}
}

// GetByEmailCalled returns true if FakeStore.GetByEmail was called
func (f *FakeStore) GetByEmailCalled() bool {
	return len(f.GetByEmailCalls) != 0
}

// AssertGetByEmailCalled calls t.Error if FakeStore.GetByEmail was not called
func (f *FakeStore) AssertGetByEmailCalled(t StoreTestingT) {
	t.Helper()
	if len(f.GetByEmailCalls) == 0 {
		t.Error("FakeStore.GetByEmail not called, expected at least one")
	}
}

// GetByEmailNotCalled returns true if FakeStore.GetByEmail was not called
func (f *FakeStore) GetByEmailNotCalled() bool {
	return len(f.GetByEmailCalls) == 0
}

// AssertGetByEmailNotCalled calls t.Error if FakeStore.GetByEmail was called
func (f *FakeStore) AssertGetByEmailNotCalled(t StoreTestingT) {
	t.Helper()
	if len(f.GetByEmailCalls) != 0 {
		t.Error("FakeStore.GetByEmail called, expected none")
	}
}

// GetByEmailCalledOnce returns true if FakeStore.GetByEmail was called exactly once
func (f *FakeStore) GetByEmailCalledOnce() bool {
	return len(f.GetByEmailCalls) == 1
}

// AssertGetByEmailCalledOnce calls t.Error if FakeStore.GetByEmail was not called exactly once
func (f *FakeStore) AssertGetByEmailCalledOnce(t StoreTestingT) {
	t.Helper()
	if len(f.GetByEmailCalls) != 1 {
		t.Errorf("FakeStore.GetByEmail called %d times, expected 1", len(f.GetByEmailCalls))
	}
}

// GetByEmailCalledN returns true if FakeStore.GetByEmail was called at least n times
func (f *FakeStore) GetByEmailCalledN(n int) bool {
	return len(f.GetByEmailCalls) >= n
}

// AssertGetByEmailCalledN calls t.Error if FakeStore.GetByEmail was called less than n times
func (f *FakeStore) AssertGetByEmailCalledN(t StoreTestingT, n int) {
	t.Helper()
	if len(f.GetByEmailCalls) < n {
		t.Errorf("FakeStore.GetByEmail called %d times, expected >= %d", len(f.GetByEmailCalls), n)
	}
}

// GetByEmailCalledWith returns true if FakeStore.GetByEmail was called with the given values
func (f_sym14 *FakeStore) GetByEmailCalledWith(ident1 string) bool {
	for _, call_sym14 := range f_sym14.GetByEmailCalls {
		if reflect.DeepEqual(call_sym14.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertGetByEmailCalledWith calls t.Error if FakeStore.GetByEmail was not called with the given values
func (f_sym15 *FakeStore) AssertGetByEmailCalledWith(t StoreTestingT, ident1 string) {
	t.Helper()
	var found_sym15 bool
	for _, call_sym15 := range f_sym15.GetByEmailCalls {
		if reflect.DeepEqual(call_sym15.Parameters.Ident1, ident1) {
			found_sym15 = true
			break
		}
	}

	if !found_sym15 {
		t.Error("FakeStore.GetByEmail not called with expected parameters")
	}
}

// GetByEmailCalledOnceWith returns true if FakeStore.GetByEmail was called exactly once with the given values
func (f_sym16 *FakeStore) GetByEmailCalledOnceWith(ident1 string) bool {
	var count_sym16 int
	for _, call_sym16 := range f_sym16.GetByEmailCalls {
		if reflect.DeepEqual(call_sym16.Parameters.Ident1, ident1) {
			count_sym16++
		}
	}

	return count_sym16 == 1
}

// AssertGetByEmailCalledOnceWith calls t.Error if FakeStore.GetByEmail was not called exactly once with the given values
func (f_sym17 *FakeStore) AssertGetByEmailCalledOnceWith(t StoreTestingT, ident1 string) {
	t.Helper()
	var count_sym17 int
	for _, call_sym17 := range f_sym17.GetByEmailCalls {
		if reflect.DeepEqual(call_sym17.Parameters.Ident1, ident1) {
			count_sym17++
		}
	}

	if count_sym17 != 1 {
		t.Errorf("FakeStore.GetByEmail called %d times with expected parameters, expected one", count_sym17)
	}
}

// GetByEmailResultsForCall returns the result values for the first call to FakeStore.GetByEmail with the given values
func (f_sym18 *FakeStore) GetByEmailResultsForCall(ident1 string) (ident2 *User, ident3 error, found_sym18 bool) {
	for _, call_sym18 := range f_sym18.GetByEmailCalls {
		if reflect.DeepEqual(call_sym18.Parameters.Ident1, ident1) {
			ident2 = call_sym18.Results.Ident2
			ident3 = call_sym18.Results.Ident3
			found_sym18 = true
			break
		}
	}

	return
}

func (f_sym19 *FakeStore) GetByID(ident1 kallax.ULID) (ident2 *User, ident3 error) {
	if f_sym19.GetByIDHook == nil {
		panic("Store.GetByID() called but FakeStore.GetByIDHook is nil")
	}

	invocation_sym19 := new(StoreGetByIDInvocation)
	f_sym19.GetByIDCalls = append(f_sym19.GetByIDCalls, invocation_sym19)

	invocation_sym19.Parameters.Ident1 = ident1

	ident2, ident3 = f_sym19.GetByIDHook(ident1)

	invocation_sym19.Results.Ident2 = ident2
	invocation_sym19.Results.Ident3 = ident3

	return
}

// SetGetByIDStub configures Store.GetByID to always return the given values
func (f_sym20 *FakeStore) SetGetByIDStub(ident2 *User, ident3 error) {
	f_sym20.GetByIDHook = func(kallax.ULID) (*User, error) {
		return ident2, ident3
	}
}

// SetGetByIDInvocation configures Store.GetByID to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym21 *FakeStore) SetGetByIDInvocation(calls_sym21 []*StoreGetByIDInvocation, fallback_sym21 func() (*User, error)) {
	f_sym21.GetByIDHook = func(ident1 kallax.ULID) (ident2 *User, ident3 error) {
		for _, call_sym21 := range calls_sym21 {
			if reflect.DeepEqual(call_sym21.Parameters.Ident1, ident1) {
				ident2 = call_sym21.Results.Ident2
				ident3 = call_sym21.Results.Ident3

				return
			}
		}

		return fallback_sym21()
	}
}

// GetByIDCalled returns true if FakeStore.GetByID was called
func (f *FakeStore) GetByIDCalled() bool {
	return len(f.GetByIDCalls) != 0
}

// AssertGetByIDCalled calls t.Error if FakeStore.GetByID was not called
func (f *FakeStore) AssertGetByIDCalled(t StoreTestingT) {
	t.Helper()
	if len(f.GetByIDCalls) == 0 {
		t.Error("FakeStore.GetByID not called, expected at least one")
	}
}

// GetByIDNotCalled returns true if FakeStore.GetByID was not called
func (f *FakeStore) GetByIDNotCalled() bool {
	return len(f.GetByIDCalls) == 0
}

// AssertGetByIDNotCalled calls t.Error if FakeStore.GetByID was called
func (f *FakeStore) AssertGetByIDNotCalled(t StoreTestingT) {
	t.Helper()
	if len(f.GetByIDCalls) != 0 {
		t.Error("FakeStore.GetByID called, expected none")
	}
}

// GetByIDCalledOnce returns true if FakeStore.GetByID was called exactly once
func (f *FakeStore) GetByIDCalledOnce() bool {
	return len(f.GetByIDCalls) == 1
}

// AssertGetByIDCalledOnce calls t.Error if FakeStore.GetByID was not called exactly once
func (f *FakeStore) AssertGetByIDCalledOnce(t StoreTestingT) {
	t.Helper()
	if len(f.GetByIDCalls) != 1 {
		t.Errorf("FakeStore.GetByID called %d times, expected 1", len(f.GetByIDCalls))
	}
}

// GetByIDCalledN returns true if FakeStore.GetByID was called at least n times
func (f *FakeStore) GetByIDCalledN(n int) bool {
	return len(f.GetByIDCalls) >= n
}

// AssertGetByIDCalledN calls t.Error if FakeStore.GetByID was called less than n times
func (f *FakeStore) AssertGetByIDCalledN(t StoreTestingT, n int) {
	t.Helper()
	if len(f.GetByIDCalls) < n {
		t.Errorf("FakeStore.GetByID called %d times, expected >= %d", len(f.GetByIDCalls), n)
	}
}

// GetByIDCalledWith returns true if FakeStore.GetByID was called with the given values
func (f_sym22 *FakeStore) GetByIDCalledWith(ident1 kallax.ULID) bool {
	for _, call_sym22 := range f_sym22.GetByIDCalls {
		if reflect.DeepEqual(call_sym22.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertGetByIDCalledWith calls t.Error if FakeStore.GetByID was not called with the given values
func (f_sym23 *FakeStore) AssertGetByIDCalledWith(t StoreTestingT, ident1 kallax.ULID) {
	t.Helper()
	var found_sym23 bool
	for _, call_sym23 := range f_sym23.GetByIDCalls {
		if reflect.DeepEqual(call_sym23.Parameters.Ident1, ident1) {
			found_sym23 = true
			break
		}
	}

	if !found_sym23 {
		t.Error("FakeStore.GetByID not called with expected parameters")
	}
}

// GetByIDCalledOnceWith returns true if FakeStore.GetByID was called exactly once with the given values
func (f_sym24 *FakeStore) GetByIDCalledOnceWith(ident1 kallax.ULID) bool {
	var count_sym24 int
	for _, call_sym24 := range f_sym24.GetByIDCalls {
		if reflect.DeepEqual(call_sym24.Parameters.Ident1, ident1) {
			count_sym24++
		}
	}

	return count_sym24 == 1
}

// AssertGetByIDCalledOnceWith calls t.Error if FakeStore.GetByID was not called exactly once with the given values
func (f_sym25 *FakeStore) AssertGetByIDCalledOnceWith(t StoreTestingT, ident1 kallax.ULID) {
	t.Helper()
	var count_sym25 int
	for _, call_sym25 := range f_sym25.GetByIDCalls {
		if reflect.DeepEqual(call_sym25.Parameters.Ident1, ident1) {
			count_sym25++
		}
	}

	if count_sym25 != 1 {
		t.Errorf("FakeStore.GetByID called %d times with expected parameters, expected one", count_sym25)
	}
}

// GetByIDResultsForCall returns the result values for the first call to FakeStore.GetByID with the given values
func (f_sym26 *FakeStore) GetByIDResultsForCall(ident1 kallax.ULID) (ident2 *User, ident3 error, found_sym26 bool) {
	for _, call_sym26 := range f_sym26.GetByIDCalls {
		if reflect.DeepEqual(call_sym26.Parameters.Ident1, ident1) {
			ident2 = call_sym26.Results.Ident2
			ident3 = call_sym26.Results.Ident3
			found_sym26 = true
			break
		}
	}

	return
}
