// generated by "charlatan -output=user_service_charlatan_test.go Service".  DO NOT EDIT.

package user

import "reflect"

// ServiceGetInvocation represents a single call of FakeService.Get
type ServiceGetInvocation struct {
	Parameters struct {
		Ident1 string
	}
	Results struct {
		Ident2 *User
		Ident3 error
	}
}

// NewServiceGetInvocation creates a new instance of ServiceGetInvocation
func NewServiceGetInvocation(ident1 string, ident2 *User, ident3 error) *ServiceGetInvocation {
	invocation := new(ServiceGetInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2
	invocation.Results.Ident3 = ident3

	return invocation
}

// ServiceSaveInvocation represents a single call of FakeService.Save
type ServiceSaveInvocation struct {
	Parameters struct {
		Ident1 *User
	}
	Results struct {
		Ident2 error
	}
}

// NewServiceSaveInvocation creates a new instance of ServiceSaveInvocation
func NewServiceSaveInvocation(ident1 *User, ident2 error) *ServiceSaveInvocation {
	invocation := new(ServiceSaveInvocation)

	invocation.Parameters.Ident1 = ident1

	invocation.Results.Ident2 = ident2

	return invocation
}

// ServiceTestingT represents the methods of "testing".T used by charlatan Fakes.  It avoids importing the testing package.
type ServiceTestingT interface {
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Helper()
}

/*
FakeService is a mock implementation of Service for testing.
Use it in your tests as in this example:

	package example

	func TestWithService(t *testing.T) {
		f := &user.FakeService{
			GetHook: func(ident1 string) (ident2 *User, ident3 error) {
				// ensure parameters meet expections, signal errors using t, etc
				return
			},
		}

		// test code goes here ...

		// assert state of FakeGet ...
		f.AssertGetCalledOnce(t)
	}

Create anonymous function implementations for only those interface methods that
should be called in the code under test.  This will force a panic if any
unexpected calls are made to FakeGet.
*/
type FakeService struct {
	GetHook  func(string) (*User, error)
	SaveHook func(*User) error

	GetCalls  []*ServiceGetInvocation
	SaveCalls []*ServiceSaveInvocation
}

// NewFakeServiceDefaultPanic returns an instance of FakeService with all hooks configured to panic
func NewFakeServiceDefaultPanic() *FakeService {
	return &FakeService{
		GetHook: func(string) (ident2 *User, ident3 error) {
			panic("Unexpected call to Service.Get")
		},
		SaveHook: func(*User) (ident2 error) {
			panic("Unexpected call to Service.Save")
		},
	}
}

// NewFakeServiceDefaultFatal returns an instance of FakeService with all hooks configured to call t.Fatal
func NewFakeServiceDefaultFatal(t_sym1 ServiceTestingT) *FakeService {
	return &FakeService{
		GetHook: func(string) (ident2 *User, ident3 error) {
			t_sym1.Fatal("Unexpected call to Service.Get")
			return
		},
		SaveHook: func(*User) (ident2 error) {
			t_sym1.Fatal("Unexpected call to Service.Save")
			return
		},
	}
}

// NewFakeServiceDefaultError returns an instance of FakeService with all hooks configured to call t.Error
func NewFakeServiceDefaultError(t_sym2 ServiceTestingT) *FakeService {
	return &FakeService{
		GetHook: func(string) (ident2 *User, ident3 error) {
			t_sym2.Error("Unexpected call to Service.Get")
			return
		},
		SaveHook: func(*User) (ident2 error) {
			t_sym2.Error("Unexpected call to Service.Save")
			return
		},
	}
}

func (f *FakeService) Reset() {
	f.GetCalls = []*ServiceGetInvocation{}
	f.SaveCalls = []*ServiceSaveInvocation{}
}

func (f_sym3 *FakeService) Get(ident1 string) (ident2 *User, ident3 error) {
	if f_sym3.GetHook == nil {
		panic("Service.Get() called but FakeService.GetHook is nil")
	}

	invocation_sym3 := new(ServiceGetInvocation)
	f_sym3.GetCalls = append(f_sym3.GetCalls, invocation_sym3)

	invocation_sym3.Parameters.Ident1 = ident1

	ident2, ident3 = f_sym3.GetHook(ident1)

	invocation_sym3.Results.Ident2 = ident2
	invocation_sym3.Results.Ident3 = ident3

	return
}

// SetGetStub configures Service.Get to always return the given values
func (f_sym4 *FakeService) SetGetStub(ident2 *User, ident3 error) {
	f_sym4.GetHook = func(string) (*User, error) {
		return ident2, ident3
	}
}

// SetGetInvocation configures Service.Get to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym5 *FakeService) SetGetInvocation(calls_sym5 []*ServiceGetInvocation, fallback_sym5 func() (*User, error)) {
	f_sym5.GetHook = func(ident1 string) (ident2 *User, ident3 error) {
		for _, call_sym5 := range calls_sym5 {
			if reflect.DeepEqual(call_sym5.Parameters.Ident1, ident1) {
				ident2 = call_sym5.Results.Ident2
				ident3 = call_sym5.Results.Ident3

				return
			}
		}

		return fallback_sym5()
	}
}

// GetCalled returns true if FakeService.Get was called
func (f *FakeService) GetCalled() bool {
	return len(f.GetCalls) != 0
}

// AssertGetCalled calls t.Error if FakeService.Get was not called
func (f *FakeService) AssertGetCalled(t ServiceTestingT) {
	t.Helper()
	if len(f.GetCalls) == 0 {
		t.Error("FakeService.Get not called, expected at least one")
	}
}

// GetNotCalled returns true if FakeService.Get was not called
func (f *FakeService) GetNotCalled() bool {
	return len(f.GetCalls) == 0
}

// AssertGetNotCalled calls t.Error if FakeService.Get was called
func (f *FakeService) AssertGetNotCalled(t ServiceTestingT) {
	t.Helper()
	if len(f.GetCalls) != 0 {
		t.Error("FakeService.Get called, expected none")
	}
}

// GetCalledOnce returns true if FakeService.Get was called exactly once
func (f *FakeService) GetCalledOnce() bool {
	return len(f.GetCalls) == 1
}

// AssertGetCalledOnce calls t.Error if FakeService.Get was not called exactly once
func (f *FakeService) AssertGetCalledOnce(t ServiceTestingT) {
	t.Helper()
	if len(f.GetCalls) != 1 {
		t.Errorf("FakeService.Get called %d times, expected 1", len(f.GetCalls))
	}
}

// GetCalledN returns true if FakeService.Get was called at least n times
func (f *FakeService) GetCalledN(n int) bool {
	return len(f.GetCalls) >= n
}

// AssertGetCalledN calls t.Error if FakeService.Get was called less than n times
func (f *FakeService) AssertGetCalledN(t ServiceTestingT, n int) {
	t.Helper()
	if len(f.GetCalls) < n {
		t.Errorf("FakeService.Get called %d times, expected >= %d", len(f.GetCalls), n)
	}
}

// GetCalledWith returns true if FakeService.Get was called with the given values
func (f_sym6 *FakeService) GetCalledWith(ident1 string) bool {
	for _, call_sym6 := range f_sym6.GetCalls {
		if reflect.DeepEqual(call_sym6.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertGetCalledWith calls t.Error if FakeService.Get was not called with the given values
func (f_sym7 *FakeService) AssertGetCalledWith(t ServiceTestingT, ident1 string) {
	t.Helper()
	var found_sym7 bool
	for _, call_sym7 := range f_sym7.GetCalls {
		if reflect.DeepEqual(call_sym7.Parameters.Ident1, ident1) {
			found_sym7 = true
			break
		}
	}

	if !found_sym7 {
		t.Error("FakeService.Get not called with expected parameters")
	}
}

// GetCalledOnceWith returns true if FakeService.Get was called exactly once with the given values
func (f_sym8 *FakeService) GetCalledOnceWith(ident1 string) bool {
	var count_sym8 int
	for _, call_sym8 := range f_sym8.GetCalls {
		if reflect.DeepEqual(call_sym8.Parameters.Ident1, ident1) {
			count_sym8++
		}
	}

	return count_sym8 == 1
}

// AssertGetCalledOnceWith calls t.Error if FakeService.Get was not called exactly once with the given values
func (f_sym9 *FakeService) AssertGetCalledOnceWith(t ServiceTestingT, ident1 string) {
	t.Helper()
	var count_sym9 int
	for _, call_sym9 := range f_sym9.GetCalls {
		if reflect.DeepEqual(call_sym9.Parameters.Ident1, ident1) {
			count_sym9++
		}
	}

	if count_sym9 != 1 {
		t.Errorf("FakeService.Get called %d times with expected parameters, expected one", count_sym9)
	}
}

// GetResultsForCall returns the result values for the first call to FakeService.Get with the given values
func (f_sym10 *FakeService) GetResultsForCall(ident1 string) (ident2 *User, ident3 error, found_sym10 bool) {
	for _, call_sym10 := range f_sym10.GetCalls {
		if reflect.DeepEqual(call_sym10.Parameters.Ident1, ident1) {
			ident2 = call_sym10.Results.Ident2
			ident3 = call_sym10.Results.Ident3
			found_sym10 = true
			break
		}
	}

	return
}

func (f_sym11 *FakeService) Save(ident1 *User) (ident2 error) {
	if f_sym11.SaveHook == nil {
		panic("Service.Save() called but FakeService.SaveHook is nil")
	}

	invocation_sym11 := new(ServiceSaveInvocation)
	f_sym11.SaveCalls = append(f_sym11.SaveCalls, invocation_sym11)

	invocation_sym11.Parameters.Ident1 = ident1

	ident2 = f_sym11.SaveHook(ident1)

	invocation_sym11.Results.Ident2 = ident2

	return
}

// SetSaveStub configures Service.Save to always return the given values
func (f_sym12 *FakeService) SetSaveStub(ident2 error) {
	f_sym12.SaveHook = func(*User) error {
		return ident2
	}
}

// SetSaveInvocation configures Service.Save to return the given results when called with the given parameters
// If no match is found for an invocation the result(s) of the fallback function are returned
func (f_sym13 *FakeService) SetSaveInvocation(calls_sym13 []*ServiceSaveInvocation, fallback_sym13 func() error) {
	f_sym13.SaveHook = func(ident1 *User) (ident2 error) {
		for _, call_sym13 := range calls_sym13 {
			if reflect.DeepEqual(call_sym13.Parameters.Ident1, ident1) {
				ident2 = call_sym13.Results.Ident2

				return
			}
		}

		return fallback_sym13()
	}
}

// SaveCalled returns true if FakeService.Save was called
func (f *FakeService) SaveCalled() bool {
	return len(f.SaveCalls) != 0
}

// AssertSaveCalled calls t.Error if FakeService.Save was not called
func (f *FakeService) AssertSaveCalled(t ServiceTestingT) {
	t.Helper()
	if len(f.SaveCalls) == 0 {
		t.Error("FakeService.Save not called, expected at least one")
	}
}

// SaveNotCalled returns true if FakeService.Save was not called
func (f *FakeService) SaveNotCalled() bool {
	return len(f.SaveCalls) == 0
}

// AssertSaveNotCalled calls t.Error if FakeService.Save was called
func (f *FakeService) AssertSaveNotCalled(t ServiceTestingT) {
	t.Helper()
	if len(f.SaveCalls) != 0 {
		t.Error("FakeService.Save called, expected none")
	}
}

// SaveCalledOnce returns true if FakeService.Save was called exactly once
func (f *FakeService) SaveCalledOnce() bool {
	return len(f.SaveCalls) == 1
}

// AssertSaveCalledOnce calls t.Error if FakeService.Save was not called exactly once
func (f *FakeService) AssertSaveCalledOnce(t ServiceTestingT) {
	t.Helper()
	if len(f.SaveCalls) != 1 {
		t.Errorf("FakeService.Save called %d times, expected 1", len(f.SaveCalls))
	}
}

// SaveCalledN returns true if FakeService.Save was called at least n times
func (f *FakeService) SaveCalledN(n int) bool {
	return len(f.SaveCalls) >= n
}

// AssertSaveCalledN calls t.Error if FakeService.Save was called less than n times
func (f *FakeService) AssertSaveCalledN(t ServiceTestingT, n int) {
	t.Helper()
	if len(f.SaveCalls) < n {
		t.Errorf("FakeService.Save called %d times, expected >= %d", len(f.SaveCalls), n)
	}
}

// SaveCalledWith returns true if FakeService.Save was called with the given values
func (f_sym14 *FakeService) SaveCalledWith(ident1 *User) bool {
	for _, call_sym14 := range f_sym14.SaveCalls {
		if reflect.DeepEqual(call_sym14.Parameters.Ident1, ident1) {
			return true
		}
	}

	return false
}

// AssertSaveCalledWith calls t.Error if FakeService.Save was not called with the given values
func (f_sym15 *FakeService) AssertSaveCalledWith(t ServiceTestingT, ident1 *User) {
	t.Helper()
	var found_sym15 bool
	for _, call_sym15 := range f_sym15.SaveCalls {
		if reflect.DeepEqual(call_sym15.Parameters.Ident1, ident1) {
			found_sym15 = true
			break
		}
	}

	if !found_sym15 {
		t.Error("FakeService.Save not called with expected parameters")
	}
}

// SaveCalledOnceWith returns true if FakeService.Save was called exactly once with the given values
func (f_sym16 *FakeService) SaveCalledOnceWith(ident1 *User) bool {
	var count_sym16 int
	for _, call_sym16 := range f_sym16.SaveCalls {
		if reflect.DeepEqual(call_sym16.Parameters.Ident1, ident1) {
			count_sym16++
		}
	}

	return count_sym16 == 1
}

// AssertSaveCalledOnceWith calls t.Error if FakeService.Save was not called exactly once with the given values
func (f_sym17 *FakeService) AssertSaveCalledOnceWith(t ServiceTestingT, ident1 *User) {
	t.Helper()
	var count_sym17 int
	for _, call_sym17 := range f_sym17.SaveCalls {
		if reflect.DeepEqual(call_sym17.Parameters.Ident1, ident1) {
			count_sym17++
		}
	}

	if count_sym17 != 1 {
		t.Errorf("FakeService.Save called %d times with expected parameters, expected one", count_sym17)
	}
}

// SaveResultsForCall returns the result values for the first call to FakeService.Save with the given values
func (f_sym18 *FakeService) SaveResultsForCall(ident1 *User) (ident2 error, found_sym18 bool) {
	for _, call_sym18 := range f_sym18.SaveCalls {
		if reflect.DeepEqual(call_sym18.Parameters.Ident1, ident1) {
			ident2 = call_sym18.Results.Ident2
			found_sym18 = true
			break
		}
	}

	return
}
